name: Windows RDP via Ngrok

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up job
      run: echo "Starting RDP setup..."

    - name: Install Ngrok
      run: |
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath $env:USERPROFILE
        Remove-Item ngrok.zip

    - name: Auth Ngrok
      run: .\ngrok\ngrok.exe authtoken YOUR_NGROK_AUTH_TOKEN

    - name: Enable RDP + Start Tunnel
      run: |
        net user DevUser Cpl@x_82Yw9! /add
        net localgroup administrators DevUser /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" `
          -ArgumentList "tcp 3389" `
          -RedirectStandardOutput "$env:USERPROFILE\ngrok.log"

    - name: Show RDP Login Info
      run: |
        echo "🔐 Username: DevUser"
        echo "🔐 Password: Cpl@x_82Yw9!"
        echo "⏳ Wait 30 seconds then read Ngrok log below..."

    - name: Show Ngrok TCP Address
      run: Get-Content "$env:USERPROFILE\ngrok.log"
